# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetest',
            name='correct_answer',
            field=models.TextField(max_length=100),
        ),
    ]
