# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170522_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='test_method',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
