# Generated by Django 2.1.2 on 2018-12-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20181203_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.PositiveIntegerField(choices=[(0, 'Python'), (1, 'C'), (2, 'C++'), (3, 'Java')], max_length=6),
        ),
    ]
